version: '3.4'

services:
  yarn:
    build:
      context: ./
      dockerfile: Dockerfile
      target: dev
    volumes:
      - './:/srv/app'
    working_dir: /srv/app
    environment:
      - "USER=${USER}"
    ports:
      - 80:3000
    command: yarn start
